services:
  aggregator:
    build:
      context: ./aggregator-service
      dockerfile: Dockerfile
    image: fireboy30/aggregator-service:latest
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_URL=static://user-service:6565
      - TRADING_SERVICE_URL=static://stock-trading-service:7575
    depends_on:
      - user-service
      - stock-trading-service

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: fireboy30/user-service:latest
    ports:
      - "6565:6565"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=userData
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
    depends_on:
      - mysql

  stock-trading-service:
    build:
      context: ./stock-trading-service
      dockerfile: Dockerfile
    image: fireboy30/stock-trading-service:latest
    ports:
      - "7575:7575"

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=userData
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  default:
    driver: bridge
volumes:
  mysql_data: