services:
  aggregator:
    build:
      context: ./aggregator-service
      dockerfile: Dockerfile
    image: fireboy30/aggregator-service:latest
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_URL=http://user-service:6565
      - TRADING_SERVICE_URL=http://stock-trading-service:7575
    depends_on:
      - user-service
      - stock-trading-service

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: fireboy30/user-service:latest
    ports:
      - "6565:6565"

  stock-trading-service:
    build:
      context: ./stock-trading-service
      dockerfile: Dockerfile
    image: fireboy30/stock-trading-service:latest
    ports:
      - "7575:7575"

networks:
  default:
    driver: bridge